---

- hosts: monitoring
  user: root

  tasks:
   - name: Install PIP
     pacman: name=python-pip state=installed

   - name: Install lxml
     pacman: name=python-lxml state=installed

   - name: Install rrdtool
     pacman: name=rrdtool state=installed

   - name: Clone home monitoring server repository
     git: repo=https://github.com/nablaa/home-monitoring-server.git dest=/home/pi/monitoring

   - name: Set repository permissions
     file: path=/home/pi/monitoring owner=pi group=pi recurse=yes

   - name: Install required Python packages
     pip: requirements=/home/pi/monitoring/requirements.txt

   - name: Copy home monitoring server config file
     copy: src=data/home-monitoring-server-configs/config.json dest=/home/pi/monitoring/config.json owner=pi group=pi mode=0644

   - name: Copy home monitoring web server password file
     copy: src=data/home-monitoring-server-configs/password dest=/home/pi/monitoring/password owner=pi group=pi mode=0600

   - name: Copy home monitoring web server certificate
     copy: src=data/home-monitoring-server-configs/server.crt dest=/home/pi/monitoring/server.crt owner=pi group=pi mode=0600

   - name: Copy home monitoring web server certificate key
     copy: src=data/home-monitoring-server-configs/server.key dest=/home/pi/monitoring/server.key owner=pi group=pi mode=0600

   - name: Copy home-monitoring-data-collection service config
     copy: src=data/home-monitoring-data-collection-service dest=/etc/systemd/system/home-monitoring-data-collection.service owner=root group=root mode=0644
     notify:
       - setup home-monitoring-data-collection service

   - name: Copy home-monitoring-web-server service config
     copy: src=data/home-monitoring-web-server-service dest=/etc/systemd/system/home-monitoring-web-server.service owner=root group=root mode=0644
     notify:
       - setup home-monitoring-web-server service

   - name: Copy home-monitoring-create-graphs service config
     copy: src=data/home-monitoring-create-graphs-service dest=/etc/systemd/system/home-monitoring-create-graphs.service owner=root group=root mode=0644

   - name: Copy home-monitoring-create-graphs timer config
     copy: src=data/home-monitoring-create-graphs-timer dest=/etc/systemd/system/home-monitoring-create-graphs.timer owner=root group=root mode=0644
     notify:
       - setup home-monitoring-create-graphs timer

  handlers:
   - name: setup home-monitoring-data-collection service
     file: src=/etc/systemd/system/home-monitoring-data-collection.service dest=/etc/systemd/system/multi-user.target.wants/home-monitoring-data-collection.service owner=root group=root state=link
     notify: start home-monitoring-data-collection service

   - name: setup home-monitoring-web-server service
     file: src=/etc/systemd/system/home-monitoring-web-server.service dest=/etc/systemd/system/multi-user.target.wants/home-monitoring-web-server.service owner=root group=root state=link
     notify: start home-monitoring-web-server service

   - name: setup home-monitoring-create-graphs timer
     file: src=/etc/systemd/system/home-monitoring-create-graphs.timer dest=/etc/systemd/system/timers.target.wants/home-monitoring-create-graphs.timer owner=root group=root state=link
     notify: start home-monitoring-create-graphs timer

   - name: start home-monitoring-data-collection service
     service: name=home-monitoring-data-collection state=started

   - name: start home-monitoring-web-server service
     service: name=home-monitoring-web-server state=started

   - name: start home-monitoring-create-graphs timer
     service: name=home-monitoring-create-graphs.timer state=started

# vim:ft=ansible:
