---

- hosts: monitoring
  user: root
  sudo: no
  vars:
    # created with:
    # python -c 'import crypt; print crypt.crypt("This is my Password", "salt")'
    password: kzsNjZylpLRrg

  tasks:
   - name: Create user pi
     user: name=pi password={{password}}

   - name: Set up authorized_keys for root user
     authorized_key: user=root key="{{ lookup('file', 'public_keys/lambda') }}"

   - name: Set up authorized_keys for pi user
     authorized_key: user=pi
                     key="{{ item }}"
     with_file:
       - public_keys/lambda
       - public_keys/mu

   - name: Set hostname
     lineinfile: dest=/etc/hostname regexp=.* line={{ machinename }}

   - name: Disallow SSH password authentication
     lineinfile:
       dest=/etc/ssh/sshd_config
       regexp="^PasswordAuthentication"
       line="PasswordAuthentication no"
       state=present
     notify:
       - restart sshd

   - name: Set timezone
     file: src=/usr/share/zoneinfo/Europe/Helsinki dest=/etc/localtime owner=root group=root state=link

   - name: Install NTP
     pacman: name=ntp state=installed

   - name: Enable NTP daemon
     service: name=ntpd enabled=yes state=restarted

  handlers:
   - name: restart sshd
     service:
       name=sshd
       state=restarted
