---

- name: GPU memory on Raspberry Pi
  lineinfile:
    dest=/boot/config.txt
    regexp="gpu_mem="
    line="gpu_mem=16"
    state=present

- name: Create user {{ user_name }}
  user: name={{ user_name }} password={{password}}

- name: Set password for root
  user: name=root password={{password}} update_password=always

- name: Set up authorized_keys for root user
  authorized_key: user=root
                  key="{{ item }}"
  with_file:
    - public_keys/lambda

- name: Set up authorized_keys for {{ user_name }} user
  authorized_key: user={{ user_name }}
                  key="{{ item }}"
  with_file:
    - public_keys/lambda

- name: Set hostname
  lineinfile: dest=/etc/hostname regexp=.* line={{ machinename }}

- name: Disallow SSH password authentication
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="PasswordAuthentication"
    line="PasswordAuthentication no"
    state=present
  notify:
    - restart sshd

- name: Enable Finland Pacman mirror
  lineinfile:
    dest=/etc/pacman.d/mirrorlist
    regexp="fi.mirror.archlinuxarm.org"
    line="Server = http://fi.mirror.archlinuxarm.org/$arch/$repo"
    state=present

- name: Update Pacman cache
  pacman: update_cache=yes

- name: Set timezone
  file: src=/usr/share/zoneinfo/Europe/Helsinki dest=/etc/localtime owner=root group=root state=link

- name: Install NTP
  pacman: name=ntp state=installed

- name: Enable NTP daemon
  service: name=ntpd enabled=yes state=started

- name: Install common packages
  pacman: name={{ item }} state=installed
  with_items:
    - autoconf
    - automake
    - binutils
    - bison
    - fakeroot
    - file
    - findutils
    - flex
    - gawk
    - gcc
    - gettext
    - grep
    - groff
    - gzip
    - libtool
    - m4
    - make
    - patch
    - pkg-config
    - sed
    - sudo
    - texinfo
    - util-linux
    - which
    - git
    - htop
    - iotop
    - rsync
    - rxvt-unicode-terminfo
    - tmux
    - vim
    - wget
    - ufw

- name: Set system log max size
  lineinfile:
    dest=/etc/systemd/journald.conf
    regexp="SystemMaxUse="
    line="SystemMaxUse=50M"
    state=present

- name: Allow SSH through firewall
  ufw: rule=allow name=ssh

- name: Enable firewall
  ufw: state=enabled policy=deny direction=incoming
