---

- name: Install required packages
  pacman: name={{ item }} state=installed
  with_items:
    - python-pip
    - python-lxml
    - rrdtool

- name: Clone home monitoring server repository
  git: repo=https://github.com/nablaa/home-monitoring-server.git
       dest={{ repo_path }}

- name: Set repository permissions
  file: path={{ repo_path }}
        owner={{ user_name }} group={{ user_name }} recurse=yes

- name: Install required Python packages
  pip: requirements={{ repo_path }}/requirements.txt

- name: Copy home monitoring server config files
  copy: src=home-monitoring-server-configs/{{ item }}
        dest={{ repo_path }}/{{ item }}
        owner={{ user_name }} group={{ user_name }} mode=0600
  with_items:
    - config.json
    - password
    - server.crt
    - server.key

- name: Copy home monitoring server service configs
  template: src=service.j2
            dest=/etc/systemd/system/{{ item.name }}.service
            owner=root group=root mode=0644
  with_items:
    - { name: "home-monitoring-data-collection",
        description: "Start home monitoring data collection service",
        command: "monitoring.py config.json",
        restart: True }
    - { name: "home-monitoring-web-server",
        description: "Start home monitoring web server service",
        command: "server.py",
        restart: True }
    - { name: "home-monitoring-create-graphs",
        description: "Start home monitoring graph creation service",
        command: "create_graphs.py -o static/images/temperatures config.json",
        restart: False }
  notify:
    - setup home monitoring server services

- name: Copy home monitoring server timer configs
  copy: src={{ item }}
        dest=/etc/systemd/system/{{ item }}
        owner=root group=root mode=0644
  with_items:
    - home-monitoring-create-graphs.timer
  notify:
    - setup home monitoring server timers

- name: Allow connection through firewall
  ufw: rule=allow port=12300 proto=tcp
