---

- name: Install required packages
  pacman: name={{ item }} state=installed
  with_items:
    - python-pip
    - python-lxml
    - rrdtool

- name: Clone home monitoring server repository
  git: repo=https://github.com/nablaa/home-monitoring-server.git
       dest=/home/{{ user_name }}/monitoring

- name: Set repository permissions
  file: path=/home/{{ user_name }}/monitoring
        owner={{ user_name }} group={{ user_name }} recurse=yes

- name: Install required Python packages
  pip: requirements=/home/{{ user_name }}/monitoring/requirements.txt

- name: Copy home monitoring server config files
  copy: src=home-monitoring-server-configs/{{ item }}
        dest=/home/{{ user_name }}/monitoring/{{ item }}
        owner={{ user_name }} group={{ user_name }} mode=0600
  with_items:
    - config.json
    - password
    - server.crt
    - server.key

- name: Copy home monitoring server service configs
  copy: src={{ item }}
        dest=/etc/systemd/system/{{ item }}
        owner=root group=root mode=0644
  with_items:
    - home-monitoring-data-collection.service
    - home-monitoring-web-server.service
    - home-monitoring-create-graphs.service
    - home-monitoring-create-graphs.timer
  notify:
    - setup home monitoring server services
