---

- name: setup home monitoring server services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - home-monitoring-data-collection.service
    - home-monitoring-web-server.service
    - home-monitoring-create-graphs.timer
